version: '3.8'
services:
  api:
    build:
      context: ./dotnet
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: product_db
      MYSQL_USER: product-api
      MYSQL_PASSWORD: securepass
      MYSQL_ROOT_PASSWORD: securepass
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
